name: Build debug

on:
    workflow_dispatch:
    push:
        branches:
          - "*"

jobs:
    build_apk:
        name: Build APK
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
                distribution: 'zulu'
                java-version: '17'
          - run: df -h
          - run: chmod +x gradlew
          - run: ./gradlew assembleDebug --info
          - uses: actions/upload-artifact@v4
            with:
                name: app-debug.apk
                path: TMessageProj/build/outputs/apk/debug/app-debug.apk
