name: Build debug

on:
    workflow_dispatch:
    push:
        branches:
          - "*"

jobs:
    build_apk:
        name: Build APK
        runs-on: ubuntu-latest
        steps:
          - name: Cleanup some space
            uses: easimon/maximize-build-space@master
            with:
                remove-dotnet: 'true'
                remove-haskell: 'true'
                remove-codeql: 'true'
                remove-docker-images: 'true'
                root-reserve-mb: 32768
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
                distribution: 'zulu'
                java-version: '17'
          - run: df -h
          - run: chmod +x gradlew
          - run: ./gradlew assembleDebug --info
          - run: find . -type f -name *.apk
          - uses: actions/upload-artifact@v4
            with:
                name: app-debug.apk
                path: '**/*.apk'
