name: Build debug

on:
    push
        branches: [ main ]

jobs:
    clone_setup_java:
        name: Clone repo and setup java
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v4
          - uses: actions/setup-java@v4
            with:
                distribution: 'coretto'
                java-version: '16'
    build_apk:
        name: Build apk
        runs-on: ubuntu-latest
        steps:
          - run: chmod +x gradlew
          - run: ./gradlew assembleDebug --info
          - uses: actions/upload-artifact@v4
            with:
                name: app-debug.apk
